spree_review/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :reviews, only: [:index, :destroy, :edit, :update] do
      member do
        get :approve
      end
      resources :feedback_reviews, only: [:index, :destroy]
    end
    resource :review_settings, only: [:edit, :update]
  end

  resources :products, only: [] do
    resources :reviews, only: [:index, :new, :create] do
    end
  end
  post '/reviews/:review_id/feedback(.:format)' => 'feedback_reviews#create', as: :feedback_reviews
end

spree_review/app/controllers/spree/admin/feedback_reviews_controller.rb
module Spree
  module Admin
    class FeedbackReviewsController < ResourceController
      belongs_to 'spree/review'

      def index
        @collection = parent.feedback_reviews
      end
    end
  end
end

spree_review/app/controllers/spree/feedback_reviews_controller.rb
class Spree::FeedbackReviewsController < Spree::StoreController
  helper Spree::BaseHelper

  before_action :sanitize_rating, only: :create
  before_action :load_review, only: :create

  def create
    if @review.present?
      @feedback_review = @review.feedback_reviews.new(feedback_review_params)
      @feedback_review.user = spree_current_user
      @feedback_review.locale = I18n.locale.to_s if Spree::Reviews::Config[:track_locale]
      authorize! :create, @feedback_review
      @feedback_review.save
    end

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js   { render action: :create }
    end
  end

  protected

  def load_review
    @review ||= Spree::Review.find_by_id!(params[:review_id])
  end

  def permitted_feedback_review_attributes
    [:rating, :comment]
  end

  def feedback_review_params
    params.require(:feedback_review).permit(permitted_feedback_review_attributes)
  end

  def sanitize_rating
    params[:feedback_review][:rating].to_s.sub!(/\s*[^0-9]*\z/, '') unless params[:feedback_review] && params[:feedback_review][:rating].blank?
  end

  def redirect_back(fallback_location:)
    if Rails.gem_version >= Gem::Version.new('5.x')
      super
    else
      redirect_to :back
    end
  end
end

spree_review/app/views/spree/admin/feedback_reviews/index.html.erb
<% content_for :page_title do %>
	<%= Spree.t(:feedback_review_for, review: @review.title) %>
<% end %>

<% content_for :page_actions do %>
	<li><%= button_link_to Spree.t(:back_reviews), admin_reviews_path, icon: 'back' %></li>
<% end %>

<% if @collection.any? %>
	<table class="table" id="listing_feedback">
		<thead>
			<tr>
				<th><%= Spree.t(:user) %></th>
				<th><%= Spree.t(:stars) %></th>
				<th><%= Spree.t(:date) %></th>
				<th data-hook="admin_feedback_index_header_actions" class="actions"></th>
			</tr>
		</thead>
		<tbody>
			<% @collection.each do |feedback| %>
				<tr id="<%= dom_id(feedback) %>" class="<%= cycle('odd', 'even') %>">
				  <td><%= feedback.user.try(:login) || Spree.t(:anonymous) %></td>
				  <td><%= feedback.rating %></td>
				  <td><%= l(feedback.created_at, format: :short) %></td>
				  <td data-hook="admin_feedback_row_header_actions" class="actions">
					  <%= link_to_delete feedback, no_text: true %>
				  </td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<div class="alert alert-info no-objects-found">
		<%= Spree.t(:no_results) %>
	</div>
<% end %>