spree_review/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :reviews, only: [:index, :destroy, :edit, :update] do
      member do
        get :approve
      end
      resources :feedback_reviews, only: [:index, :destroy]
    end
    resource :review_settings, only: [:edit, :update]
  end

  resources :products, only: [] do
    resources :reviews, only: [:index, :new, :create] do
    end
  end
  post '/reviews/:review_id/feedback(.:format)' => 'feedback_reviews#create', as: :feedback_reviews
end

spree_review/app/models/spree/feedback_review.rb
class Spree::FeedbackReview < ActiveRecord::Base
  belongs_to :user, class_name: Spree.user_class.to_s
  belongs_to :review, dependent: :destroy

  validates :review, presence: true
  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
    message: Spree.t(:you_must_enter_value_for_rating)
  }

  default_scope { most_recent_first }
  scope :most_recent_first, -> { order('spree_feedback_reviews.created_at DESC') }
  scope :localized, ->(lc) { where('spree_feedback_reviews.locale = ?', lc) }
end

spree_review/app/models/spree/product_decorator.rb
# Add access to reviews/ratings to the product model
Spree::Product.class_eval do
  has_many :reviews

  def stars
    avg_rating.try(:round) || 0
  end

  def recalculate_rating
    self[:reviews_count] = reviews.reload.approved.count
    if reviews_count > 0
      self[:avg_rating] = reviews.approved.sum(:rating).to_f / reviews_count
    else
      self[:avg_rating] = 0
    end
    save
  end
end

spree_review/app/models/spree/review.rb
class Spree::Review < ActiveRecord::Base
  belongs_to :product, touch: true
  belongs_to :user, class_name: Spree.user_class.to_s
  has_many   :feedback_reviews

  after_save :recalculate_product_rating, if: :approved?
  after_destroy :recalculate_product_rating

  validates :name, :review, presence: true
  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
    message: Spree.t(:you_must_enter_value_for_rating)
  }

  default_scope { order('spree_reviews.created_at DESC') }

  scope :localized, ->(lc) { where('spree_reviews.locale = ?', lc) }
  scope :most_recent_first, -> { order('spree_reviews.created_at DESC') }
  scope :oldest_first, -> { reorder('spree_reviews.created_at ASC') }
  scope :preview, -> { limit(Spree::Reviews::Config[:preview_size]).oldest_first }
  scope :approved, -> { where(approved: true) }
  scope :not_approved, -> { where(approved: false) }
  scope :default_approval_filter, -> { Spree::Reviews::Config[:include_unapproved_reviews] ? all : approved }

  def feedback_stars
    return 0 if feedback_reviews.size <= 0
    ((feedback_reviews.sum(:rating) / feedback_reviews.size) + 0.5).floor
  end

  def recalculate_product_rating
    product.recalculate_rating if product.present?
  end
end

spree_review/app/models/spree/review_setting.rb
module Spree
  class ReviewSetting < Preferences::Configuration
    # Include non-approved reviews in (public) listings.
    preference :include_unapproved_reviews, :boolean, default: false

    # Control how many reviews are shown in summaries etc.
    preference :preview_size, :integer, default: 3

    # Show a reviewer's email address.
    preference :show_email, :boolean, default: false

    # Show helpfullness rating form elements.
    preference :feedback_rating, :boolean, default: false

    # Require login to post reviews.
    preference :require_login, :boolean, default: true

    # Whether to keep track of the reviewer's locale.
    preference :track_locale, :boolean, default: false

    # Render checkbox for a user to approve to show their identifier
    # (name or email) on their review.
    preference :show_identifier, :boolean, default: false

    def stars
      5
    end
  end
end

spree_review/app/models/spree/reviews_ability.rb
class Spree::ReviewsAbility
  include CanCan::Ability

  def initialize(user)
    review_ability_class = self.class
    can :create, Spree::Review do
      review_ability_class.allow_anonymous_reviews? || !user.email.blank?
    end
    can :create, Spree::FeedbackReview do
      review_ability_class.allow_anonymous_reviews? || !user.email.blank?
    end
  end

  def self.allow_anonymous_reviews?
    !Spree::Reviews::Config[:require_login]
  end
end

spree_review/app/controllers/spree/admin/feedback_reviews_controller.rb
module Spree
  module Admin
    class FeedbackReviewsController < ResourceController
      belongs_to 'spree/review'

      def index
        @collection = parent.feedback_reviews
      end
    end
  end
end

spree_review/app/controllers/spree/admin/review_settings_controller.rb
module Spree
  module Admin
    class ReviewSettingsController < ResourceController

      def update
        settings = Spree::ReviewSetting.new
        preferences = params && params.key?(:preferences) ? params.delete(:preferences) : params
        preferences.each do |name, value|
          next unless settings.has_preference? name
          settings[name] = value
        end
        flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:review_settings, scope: :spree_reviews))
        redirect_to edit_admin_review_settings_path
      end
    end
  end
end

spree_review/app/controllers/spree/admin/reviews_controller.rb
class Spree::Admin::ReviewsController < Spree::Admin::ResourceController
  helper Spree::ReviewsHelper

  def index
    @reviews = collection
  end

  def approve
    review = Spree::Review.find(params[:id])
    if review.update_attribute(:approved, true)
      flash[:notice] = Spree.t(:info_approve_review)
    else
      flash[:error] = Spree.t(:error_approve_review)
    end
    redirect_to admin_reviews_path
  end

  def edit
    return if @review.product
    flash[:error] = Spree.t(:error_no_product)
    redirect_to admin_reviews_path
  end

  private

  def collection
    params[:q] ||= {}
    @search = Spree::Review.ransack(params[:q])
    @collection = @search.result.includes([:product, :user, :feedback_reviews]).page(params[:page]).per(params[:per_page])
  end
end

spree_review/app/controllers/spree/feedback_reviews_controller.rb
class Spree::FeedbackReviewsController < Spree::StoreController
  helper Spree::BaseHelper

  before_action :sanitize_rating, only: :create
  before_action :load_review, only: :create

  def create
    if @review.present?
      @feedback_review = @review.feedback_reviews.new(feedback_review_params)
      @feedback_review.user = spree_current_user
      @feedback_review.locale = I18n.locale.to_s if Spree::Reviews::Config[:track_locale]
      authorize! :create, @feedback_review
      @feedback_review.save
    end

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js   { render action: :create }
    end
  end

  protected

  def load_review
    @review ||= Spree::Review.find_by_id!(params[:review_id])
  end

  def permitted_feedback_review_attributes
    [:rating, :comment]
  end

  def feedback_review_params
    params.require(:feedback_review).permit(permitted_feedback_review_attributes)
  end

  def sanitize_rating
    params[:feedback_review][:rating].to_s.sub!(/\s*[^0-9]*\z/, '') unless params[:feedback_review] && params[:feedback_review][:rating].blank?
  end

  def redirect_back(fallback_location:)
    if Rails.gem_version >= Gem::Version.new('5.x')
      super
    else
      redirect_to :back
    end
  end
end

spree_review/app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.class_eval do
  helper Spree::ReviewsHelper

  reviews_fields = [:avg_rating, :reviews_count]
  reviews_fields.each { |attrib| Spree::PermittedAttributes.product_attributes << attrib }

  Spree::Api::ApiHelpers.class_eval do
    reviews_fields.each { |attrib| class_variable_set(:@@product_attributes, class_variable_get(:@@product_attributes).push(attrib)) }
  end
end

spree_review/app/controllers/spree/reviews_controller.rb
class Spree::ReviewsController < Spree::StoreController
  helper Spree::BaseHelper
  before_action :load_product, only: [:index, :new, :create]
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  def index
    @approved_reviews = Spree::Review.approved.where(product: @product)
  end

  def new
    @review = Spree::Review.new(product: @product)
    authorize! :create, @review
  end

  # save if all ok
  def create
    params[:review][:rating].sub!(/\s*[^0-9]*\z/, '') unless params[:review][:rating].blank?

    @review = Spree::Review.new(review_params)
    @review.product = @product
    @review.user = spree_current_user if spree_user_signed_in?
    @review.ip_address = request.remote_ip
    @review.locale = I18n.locale.to_s if Spree::Reviews::Config[:track_locale]

    authorize! :create, @review
    if @review.save
      flash[:notice] = Spree.t(:review_successfully_submitted)
      redirect_to spree.product_path(@product)
    else
      render :new
    end
  end

  private

  def load_product
    @product = Spree::Product.friendly.find(params[:product_id])
  end

  def permitted_review_attributes
    [:rating, :title, :review, :name, :show_identifier]
  end

  def review_params
    params.require(:review).permit(permitted_review_attributes)
  end
end

spree_review/app/helpers/spree/reviews_helper.rb
module Spree::ReviewsHelper
  def star(the_class)
    content_tag(:span, ' &#10030; '.html_safe, class: the_class)
  end

  def mk_stars(m)
    (1..5).collect { |n| n <= m ? star('lit') : star('unlit') }.join
  end

  def txt_stars(n, show_out_of = true)
    res = Spree.t(:star, count: n)
    res += " #{Spree.t('out_of_5')}" if show_out_of
    res
  end
end

spree_review/app/views/spree/shared/_rating.html.erb
<% stars = product.stars %>
<% reviews_count = product.reviews_count %>
<div class="ratings">
  <p><%= Spree.t(:average_customer_rating) %>:</p>
  <p class="ratings-stars">
    <span title="<%= txt_stars(stars) %>">
      <%= render 'spree/reviews/stars', stars: stars %>
    </span>
  </p>
  <p class="ratings-basedupon">(<%= Spree.t(:based_upon_review_count, count: reviews_count) %>)</p>
  <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    <span itemprop="ratingValue" content="<%= stars %>"></span>
    <span itemprop="reviewCount" content="<%= reviews_count %>"></span>
  </div>
</div>

spree_review/app/views/spree/shared/_review.html.erb
<div class="review" itemprop="reviews" itemscope itemtype="http://schema.org/Review">
  <span class="reviews-rating" title="<%= txt_stars(review.rating) %>">
    <%= render 'spree/reviews/stars', stars: review.rating %>
  </span>
  <span itemprop="name"><%= review.title %></span>
  <br/>
  <span class="attribution"><%= Spree.t(:submitted_on) %>
    <strong><%= l review.created_at.to_date %></strong>
  </span>
  <span itemprop="datePublished" content="<%= review.created_at.to_date.to_s %>"></span>
  <span itemprop="reviewRating" content="<%= review.rating %>"></span>
  <% if review.show_identifier %>
    <% if Spree::Reviews::Config[:show_email] && review.user %>
      <span itemprop="author"><%= review.user.email %></span>
    <% else %>
      <span itemprop="author"><%= review.name %></span>
    <% end %>
  <% else %>
    <span itemprop="author"><%= Spree.t(:anonymous) %></span>
  <% end %>
  <div itemprop="reviewBody">
    <%= simple_format(review.review) %>
  </div>
  <% if Spree::Reviews::Config[:feedback_rating] && (!Spree::Reviews::Config[:require_login] || spree_current_user) %>
    <div class="feedback_review" id="feedback_review_<%= review.id %>">
      <%= render 'spree/feedback_reviews/form', review: review %>
    </div>
  <% end %>
</div>

spree_review/app/views/spree/shared/_review_summary.html.erb
<div id="reviews">
  <%= render 'spree/shared/rating', locals: @product, review: 0 %>
  <% for review in (Spree::Reviews::Config[:track_locale] ? @product.reviews.localized(I18n.locale) : @product.reviews).default_approval_filter.preview %>
    <%= render 'spree/shared/review', review: review %>
  <% end %>
  <% if Spree::Reviews::Config[:feedback_rating] && (!Spree::Reviews::Config[:require_login] || spree_current_user) %>
    <%= link_to Spree.t(:write_your_own_review), new_product_review_path(@product), class: 'btn btn-default' %>
  <% end %>
</div>

spree_review/app/views/spree/shared/_reviews.html.erb
<div id="reviews">
  <h3 class="product-section-title"><%= Spree.t(:reviews) %></h3>
  <% if Spree::Reviews::Config[:include_unapproved_reviews] == false and @product.reviews.approved.count == 0 %>
    <p class="reviews-none"><%= Spree.t(:no_reviews_available) %></p>
  <% else %>
    <%= render 'spree/shared/rating', product: @product, review: 0 %>
    <% for review in (Spree::Reviews::Config[:track_locale] ? @product.reviews.localized(I18n.locale) : @product.reviews).default_approval_filter.preview %>
      <%= render 'spree/shared/review', review: review %>
    <% end %>
  <% end %>
  <%= link_to Spree.t(:write_your_own_review), new_product_review_path(@product), class: 'btn btn-default', rel: 'nofollow' %>
</div>

spree_review/app/views/spree/shared/_shortrating.html.erb
<% stars = product.stars %>
<% reviews_count = product.reviews_count %>
<div>
  <div style="float:left;" title="<%= txt_stars(stars) %>">
    <%= render 'spree/reviews/stars', stars: stars %>
  </div>
  <div style="float:right;">
    <%= Spree::Review.model_name.human(count: reviews_count) %>
  </div>
</div>