spree_review/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :reviews, only: [:index, :destroy, :edit, :update] do
      member do
        get :approve
      end
      resources :feedback_reviews, only: [:index, :destroy]
    end
    resource :review_settings, only: [:edit, :update]
  end

  resources :products, only: [] do
    resources :reviews, only: [:index, :new, :create] do
    end
  end
  post '/reviews/:review_id/feedback(.:format)' => 'feedback_reviews#create', as: :feedback_reviews
end

spree_review/app/models/spree/review_setting.rb
module Spree
  class ReviewSetting < Preferences::Configuration
    # Include non-approved reviews in (public) listings.
    preference :include_unapproved_reviews, :boolean, default: false

    # Control how many reviews are shown in summaries etc.
    preference :preview_size, :integer, default: 3

    # Show a reviewer's email address.
    preference :show_email, :boolean, default: false

    # Show helpfullness rating form elements.
    preference :feedback_rating, :boolean, default: false

    # Require login to post reviews.
    preference :require_login, :boolean, default: true

    # Whether to keep track of the reviewer's locale.
    preference :track_locale, :boolean, default: false

    # Render checkbox for a user to approve to show their identifier
    # (name or email) on their review.
    preference :show_identifier, :boolean, default: false

    def stars
      5
    end
  end
end

spree_review/app/controllers/spree/admin/review_settings_controller.rb
module Spree
  module Admin
    class ReviewSettingsController < ResourceController

      def update
        settings = Spree::ReviewSetting.new
        preferences = params && params.key?(:preferences) ? params.delete(:preferences) : params
        preferences.each do |name, value|
          next unless settings.has_preference? name
          settings[name] = value
        end
        flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:review_settings, scope: :spree_reviews))
        redirect_to edit_admin_review_settings_path
      end
    end
  end
end

spree_review/app/views/spree/admin/review_settings/edit.html.erb
<% content_for :page_title do %>
<%= Spree.t(:review_settings, scope: :spree_reviews) %>
<% end %>

<%= form_tag admin_review_settings_path, method: :put do %>
	<div class="row">
		<div class="col-md-12" data-hook="reviews">
			<div class="checkbox">
				<%= label_tag :include_unapproved_reviews do %>
					<%= preference_field_tag :include_unapproved_reviews, Spree::Reviews::Config[:include_unapproved_reviews], type: :boolean %>
					<%= Spree.t(:include_unapproved, scope: :spree_reviews) %>
				<% end %>
			</div>

			<div class="checkbox">
				<%= label_tag :feedback_rating do %>
					<%= preference_field_tag :feedback_rating, Spree::Reviews::Config[:feedback_rating], type: :boolean %>
					<%= Spree.t(:feedback_rating, scope: :spree_reviews) %>
				<% end %>
			</div>

			<div class="checkbox">
				<%= label_tag :show_email do %>
					<%= preference_field_tag :show_email, Spree::Reviews::Config[:show_email], type: :boolean %>
					<%= Spree.t(:show_email, scope: :spree_reviews) %>
				<% end %>
			</div>

			<div class="checkbox">
				<%= label_tag :require_login do %>
					<%= preference_field_tag :require_login, Spree::Reviews::Config[:require_login], type: :boolean %>
					<%= Spree.t(:require_login, scope: :spree_reviews) %>
				<% end %>
			</div>

			<div class="checkbox">
				<%= label_tag :track_locale do %>
					<%= preference_field_tag :track_locale, Spree::Reviews::Config[:track_locale], type: :boolean %>
					<%= Spree.t(:track_locale, scope: :spree_reviews) %>
				<% end %>
			</div>

			<div class="checkbox">
				<%= label_tag :show_identifier do %>
					<%= preference_field_tag :show_identifier, Spree::Reviews::Config[:show_identifier], type: :boolean %>
					<%= Spree.t(:show_identifier, scope: :spree_reviews) %>
				<% end %>
			</div>

			<div class="form-group">
				<%= label_tag Spree.t(:preview_size, scope: :spree_reviews) %>
				<%= number_field_tag :preview_size, Spree::Reviews::Config[:preview_size], class: 'form-control' %>
			</div>

			<div class="form-actions" data-hook="buttons">
				<%= button Spree.t('actions.update'), 'update' %>
			</div>
		</div>
	</div>
<% end %>